### ISSUE TITLE
Conciseness of Reference Implementation Configuration Interface

### ISSUE THREAD

**Issue by blaggacao** [openintegrationhub/openintegrationhub#1075]
Akin to #1073 , devops user and oih-developer alike want to communicate clearly the _configuration_ interface within the reference implementation as a higher yield substitute to documentation.

- A clear interface helps the developer in keeping it up to date, consistent and concise.
- A clear interface helps the devops user to understand the moving parts of an application he is supposed to reason about first.

**Further description:**

https://github.com/openintegrationhub/openintegrationhub/commit/5816a93c41821d1169acb33a91106f2f0a056691 carved out the config-type (as opposed to secret-type) configuration environment variables into transparently structured _ConfigMaps_. The `envFrom` trick avoids the need for verbose and hard-to-maintain reference string pointers since the _ConfigMap_ keys are directly transposed into environment variables.

This change already provided very concise _configmap.yaml_ configuration interfaces in the style of:
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: audit-log
  namespace: oih-dev-ns
data:
  EXCHANGE_NAME: audit-logs
  EXCHANGE_TOPIC: logs
  INTROSPECT_ENDPOINT_BASIC: "http://iam.openintegrationhub.com/api/v1/tokens/introspect"
  INTROSPECT_TYPE: basic
  QUEUE_URL: "amqp://guest:guest@rabbitmq-service.oih-dev-ns.svc.cluster.local:5672"
```

Doing the same for secret-type environment variables, would be a natural complement and would regularly expose the entire configuration api within `./services/**/k8s/config/`.

**Upside:**

- extensive code comments can be added without making the interface all too verbose
- documentation &mdash; instead of re-declaring the interface &mdash; _could_ choose to directly link to respectively code-commented file on master branch. A practice often seen in the golang world to intertwine code and documentation in the most beneficial way, even for laymen users.

**API Changes:**

- current implementation declare secrets according to present string pointer references
- they would have to restructure their secrets and update them accordingly

**Using secrets:**

This proposal does not seek to switch the way secrets are used. They can be consumed through projected volumes, which is arguably a little more secure than keeping them in the environment. This proposal acts as an excellent precursor to keep the required changes to javascript code minimal, if such path should eventually be sought after: instead of reading `VARIABLE_TOKENS` from the environment, they would be consumed from a `filesystem/path/VARIABLE_TOKEN`.

---

**Acceptance Criteria:**
- [ ] Configuration interface isolated
- [ ] Holistic review on the interface conducted &rarr; issues identified therein should result in separate issues.

---

[**Definition of done**](https://github.com/openintegrationhub/openintegrationhub/blob/contributingGuidelines/CONTRIBUTING.md#definition-of-done)
