### ISSUE TITLE
Expand ICR for service collaboration

### ISSUE THREAD

**Issue by philecs** [openintegrationhub/openintegrationhub#272]
As a product manager I want to secure interoperability of framework services so that stakeholder can easily operate the oih.

**Further description:**

To ensure interoperability of the ICR API must be expanded to be able to start/stop a flow.
Therefore the two following endpoints are needed:

We need to extend the API by the following resources:

* `POST /flows/{id}/start`: Used to start a flow
* `POST /flows/{id}/stop`: Used to stop a flow

Starting a flow means setting flow's `status` to `active` and raising `flow.starting` event. Stopping a flow means setting flow's `status` to `inactive` and raising `flow.stopping` event. The schema of the event payload is shown below.

```yaml
Event:
  type: object
  required:
    - headers
    - payload
  properties:
    headers:
      type: object
       required:
         - name
         - createdAt
      properties:
        name:
          type: string
        createdAt:
          type: string
          format: date-time
    payload:
      type: object
```

The `payload` property is an arbitrary object to be sent with the event. Flow repository will send the entire flow as `payload`. 

**We also need to extend the `flow` model in the API by the following properties:**

* ` id`: required
* `cron`: required for polling flows and defaults to `*/3 * * * *` if not set for a polling flow. Must not be set for a webhook flow.

---

**Acceptance Criteria:**
- [ ] Endpoints added
- [ ] Flow model adjusted
- [ ] Test delivered
- [ ] Endpoints checked by @DennisCES 

---

[**Definition of Done**](https://github.com/openintegrationhub/openintegrationhub/blob/crudmonitoring/CONTRIBUTING.md#definition-of-done)

**Comment by philecs** [comment]
Additionally see comment by @drobiazko in #262

**Comment by philecs** [comment]
@SvenHoeffler: @drobiazko will update #262. The flow structure is likely to be expanded by a new attribute `cron`. If set its a scheduled flow, if not set its a webhook.

But more to come.

**Comment by philecs** [comment]
#262 updated: 

We need to extend the API by the following resources:

* `POST /flows/{id}/start`: Used to start a flow
* `POST /flows/{id}/stop`: Used to stop a flow

Starting a flow means setting flow's `status` to `active` and raising `flow.starting` event. Stopping a flow means setting flow's `status` to `inactive` and raising `flow.stopping` event. The schema of the event payload is shown below.

```yaml
Event:
  type: object
  required:
    - headers
    - payload
  properties:
    headers:
      type: object
       required:
         - name
         - createdAt
      properties:
        name:
          type: string
        createdAt:
          type: string
          format: date-time
    payload:
      type: object
```

The `payload` property is an arbitrary object to be sent with the event. Flow repository will send the entire flow as `payload`. 

We also need to extend the `flow` model in the API by the following properties:

* ` id`: required
* `cron`: required for polling flows and defaults to `*/3 * * * *` if not set for a polling flow. Must not be set for a webhook flow.
